
all: problema_11_processes_with_wait problema_11_processes_with_waitpid problema_11_pthread problema_11_pthread_base

problema_11_processes_with_wait: problema_11_processes_with_wait.c  
	gcc -o problema_11_processes_with_wait problema_11_processes_with_wait.c

problema_11_processes_with_waitpid: problema_11_processes_with_waitpid.c  
	gcc -o problema_11_processes_with_waitpid problema_11_processes_with_waitpid.c

problema_11_pthread: problema_11_pthread.c         
	gcc -o problema_11_pthread problema_11_pthread.c

problema_11_pthread_base: problema_11_pthread_base.c
	gcc -o problema_11_pthread_base problema_11_pthread_base.c
	
