
all: problema1_signal problema2_shared_memory

problema1_signal: problema1_signal.c
	gcc -o problema1_signal problema1_signal.c 

problema2_shared_memory: problema2_shared_memory.c
	gcc -o problema2_shared_memory problema2_shared_memory.c
	